version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - pip install cfn-lint

  build:
    commands:
      - cfn-lint ./**/*.json
      - echo "Hello from custom specification"