formatter: "markdown table"

header-from: main.tf

sort:
  by: required

output:
  file: ../README.md
  mode: inject

settings:
  hide-empty: true
  description: true

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}